### ISSUE TITLE
Problem importing the module "custom_drawing"

### ISSUE THREAD

**Issue by mrshetab** [itap-robotica-medica/lightweight-hand-segmentation#1]
Hello, 

I cannot import the module custom_drawing. I cannot find any similar module on the internet. Would you please clarify how to fix that? Thanx!

**Comment by anooshehsaadati** [comment]
Yes, Please push extra files to repository

**Comment by anooshehsaadati** [comment]
> Hello,
> 
> I cannot import the module custom_drawing. I cannot find any similar module on the internet. Would you please clarify how to fix that? Thanx!

How do you import hands_connections?

**Comment by itap-robotica-medica** [comment]
Sorry for the delay. Both missing files have been uploaded. @anooshehsaadati @mrshetab

**Comment by anooshehsaadati** [comment]
Thanks
